# Generated by Django 6.0.6 on 2026-06-11 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tytuł')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('venue_name', models.CharField(default='Klub UCHO', max_length=200, verbose_name='nazwa miejsca')),
                ('venue_address', models.CharField(blank=True, max_length=300, verbose_name='adres')),
                ('start_at', models.DateTimeField(verbose_name='początek')),
                ('end_at', models.DateTimeField(verbose_name='koniec')),
                ('sales_start_at', models.DateTimeField(verbose_name='start sprzedaży')),
                ('sales_end_at', models.DateTimeField(verbose_name='koniec sprzedaży')),
                ('capacity_total', models.PositiveIntegerField(verbose_name='pojemność')),
                ('sold_total', models.PositiveIntegerField(default=0, verbose_name='sprzedane')),
                ('status', models.CharField(choices=[('DRAFT', 'Szkic'), ('PUBLISHED', 'Opublikowane'), ('CANCELLED', 'Odwołane'), ('FINISHED', 'Zakończone')], default='DRAFT', max_length=20)),
                ('max_tickets_per_order', models.PositiveSmallIntegerField(default=10)),
                ('calendar_event_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'wydarzenie',
                'verbose_name_plural': 'wydarzenia',
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nazwa')),
                ('priority', models.PositiveSmallIntegerField(verbose_name='priorytet')),
                ('price_gross', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='cena brutto')),
                ('currency', models.CharField(default='PLN', max_length=8)),
                ('capacity', models.PositiveIntegerField(verbose_name='pojemność puli')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='sprzedane')),
                ('sales_start_at', models.DateTimeField(blank=True, null=True, verbose_name='start sprzedaży puli')),
                ('sales_end_at', models.DateTimeField(blank=True, null=True, verbose_name='koniec sprzedaży puli')),
                ('manual_status', models.CharField(choices=[('AUTO', 'Automatyczna'), ('FORCED_OPEN', 'Wymuszona otwarta'), ('FORCED_CLOSED', 'Wymuszona zamknięta')], default='AUTO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='events.event')),
            ],
            options={
                'verbose_name': 'pula biletów',
                'verbose_name_plural': 'pule biletów',
                'ordering': ['event', 'priority'],
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('sold_total__lte', models.F('capacity_total'))), name='event_sold_within_capacity'),
        ),
        migrations.AddConstraint(
            model_name='ticketpool',
            constraint=models.CheckConstraint(condition=models.Q(('sold_count__lte', models.F('capacity'))), name='pool_sold_within_capacity'),
        ),
        migrations.AddConstraint(
            model_name='ticketpool',
            constraint=models.UniqueConstraint(fields=('event', 'priority'), name='pool_priority_unique_per_event'),
        ),
    ]
