# Generated by Django 6.0.6 on 2026-06-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPSERT', 'Utwórz/aktualizuj'), ('CANCEL', 'Usuń/odwołaj')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Oczekuje'), ('DONE', 'Wykonane'), ('FAILED', 'Błąd')], default='PENDING', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_tasks', to='events.event')),
            ],
            options={
                'verbose_name': 'zadanie kalendarza',
                'verbose_name_plural': 'zadania kalendarza',
                'ordering': ['created_at'],
            },
        ),
    ]
