# Generated by Django 6.0.6 on 2026-08-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_calendaroutbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_tickets_per_order',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='maks. biletów na zamówienie'),
        ),
    ]
