# Generated by Django 6.0.6 on 2026-09-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_max_tickets_per_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_address',
            field=models.CharField(blank=True, default='ul. Świętego Piotra 2, 81-347 Gdynia', max_length=300, verbose_name='adres'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(default='Podwórko.art / Scena UCHO', max_length=200, verbose_name='nazwa miejsca'),
        ),
    ]
