# Generated by Django 6.0.6 on 2026-09-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_venue_address_alter_event_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gates_open_at',
            field=models.DateTimeField(null=True, verbose_name='otwarcie bramek'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='koniec (jeśli znany)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_at',
            field=models.DateTimeField(verbose_name='start koncertu'),
        ),
    ]
