# Generated by Django 6.0.6 on 2026-09-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_gates_open_at_alter_event_end_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpool',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='ilość biletów'),
        ),
    ]
