# Generated by Django 6.0.6 on 2026-09-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_ticketpool_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketpool',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nazwa'),
        ),
    ]
