# Generated by Django 6.0.6 on 2026-09-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_ticketpool_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketpool',
            options={'ordering': ['event', 'sales_start_at'], 'verbose_name': 'pula biletów', 'verbose_name_plural': 'pule biletów'},
        ),
        migrations.RemoveConstraint(
            model_name='ticketpool',
            name='pool_priority_unique_per_event',
        ),
        migrations.AddField(
            model_name='ticketpool',
            name='on_sellout',
            field=models.CharField(choices=[('ACTIVATE_NEXT', 'Uruchom kolejną pulę'), ('PAUSE', 'Wstrzymaj sprzedaż')], default='ACTIVATE_NEXT', max_length=20, verbose_name='gdy się wyczerpie'),
        ),
        migrations.RemoveField(
            model_name='ticketpool',
            name='priority',
        ),
    ]
