# Generated by Django 6.0.6 on 2026-10-01 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_ticketpool_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendaroutbox',
            name='action',
            field=models.CharField(choices=[('UPSERT', 'Utwórz/aktualizuj'), ('CANCEL', 'Usuń/odwołaj')], max_length=10, verbose_name='akcja'),
        ),
        migrations.AlterField(
            model_name='calendaroutbox',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='próby'),
        ),
        migrations.AlterField(
            model_name='calendaroutbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='utworzono'),
        ),
        migrations.AlterField(
            model_name='calendaroutbox',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_tasks', to='events.event', verbose_name='wydarzenie'),
        ),
        migrations.AlterField(
            model_name='calendaroutbox',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='ostatni błąd'),
        ),
        migrations.AlterField(
            model_name='calendaroutbox',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='przetworzono'),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID w Kalendarzu Google'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='utworzono'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='utworzył(a)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='adres (slug)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='zmieniono'),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_updated', to=settings.AUTH_USER_MODEL, verbose_name='zmienił(a)'),
        ),
        migrations.AlterField(
            model_name='ticketpool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='utworzono'),
        ),
        migrations.AlterField(
            model_name='ticketpool',
            name='currency',
            field=models.CharField(default='PLN', max_length=8, verbose_name='waluta'),
        ),
        migrations.AlterField(
            model_name='ticketpool',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='events.event', verbose_name='wydarzenie'),
        ),
        migrations.AlterField(
            model_name='ticketpool',
            name='manual_status',
            field=models.CharField(choices=[('AUTO', 'Automatyczna'), ('FORCED_OPEN', 'Wymuszona otwarta'), ('FORCED_CLOSED', 'Wymuszona zamknięta')], default='AUTO', max_length=20, verbose_name='tryb ręczny'),
        ),
        migrations.AlterField(
            model_name='ticketpool',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='zmieniono'),
        ),
    ]
