# Generated by Django 6.0.6 on 2026-06-11 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='e-mail kupującego')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='liczba biletów')),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='kwota brutto')),
                ('currency', models.CharField(default='PLN', max_length=8)),
                ('status', models.CharField(choices=[('CREATED', 'Utworzone'), ('PAYMENT_PENDING', 'Oczekuje na płatność'), ('PAID', 'Opłacone'), ('FAILED', 'Nieudane'), ('EXPIRED', 'Wygasłe'), ('REFUNDED', 'Zwrócone'), ('CANCELLED', 'Anulowane')], default='CREATED', max_length=20)),
                ('payment_provider', models.CharField(choices=[('DEMO', 'Demo (waluta wirtualna)'), ('STRIPE', 'Stripe')], max_length=10)),
                ('payment_session_id', models.CharField(blank=True, max_length=200)),
                ('provider_order_id', models.CharField(blank=True, max_length=200)),
                ('is_demo', models.BooleanField(editable=False, verbose_name='zamówienie demo')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='wygasa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='events.event')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='events.ticketpool')),
            ],
            options={
                'verbose_name': 'zamówienie',
                'verbose_name_plural': 'zamówienia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('DEMO', 'Tryb demo'), ('LIVE', 'Tryb produkcyjny')], default='DEMO', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'konfiguracja płatności',
                'verbose_name_plural': 'konfiguracja płatności',
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('DEMO', 'Demo (waluta wirtualna)'), ('STRIPE', 'Stripe')], max_length=10)),
                ('provider_event_id', models.CharField(max_length=200)),
                ('event_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Odebrany'), ('PROCESSED', 'Przetworzony'), ('DUPLICATE', 'Duplikat'), ('IGNORED', 'Zignorowany'), ('ERROR', 'Błąd')], default='RECEIVED', max_length=20)),
                ('payload_hash', models.CharField(blank=True, max_length=64)),
                ('is_demo', models.BooleanField(editable=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='orders.order')),
            ],
            options={
                'verbose_name': 'zdarzenie płatności',
                'verbose_name_plural': 'zdarzenia płatności',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'expires_at'], name='orders_orde_status_62907b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer_email'], name='orders_orde_buyer_e_fd9098_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='payment_event_unique_per_provider'),
        ),
    ]
