# Generated by Django 6.0.6 on 2026-06-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
