# Generated by Django 6.0.6 on 2026-10-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_checkout_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentevent',
            options={'ordering': ['-received_at'], 'verbose_name': 'wpis dziennika płatności', 'verbose_name_plural': 'dziennik płatności'},
        ),
    ]
