# Generated by Django 6.0.6 on 2026-10-01 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_polish_field_labels'),
        ('orders', '0003_payment_log_rename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='adres kasy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='utworzono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='PLN', max_length=8, verbose_name='waluta'),
        ),
        migrations.AlterField(
            model_name='order',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='events.event', verbose_name='wydarzenie'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='opłacono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(choices=[('DEMO', 'Demo (waluta wirtualna)'), ('STRIPE', 'Stripe')], max_length=10, verbose_name='operator płatności'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID sesji płatności'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='events.ticketpool', verbose_name='pula'),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID zamówienia u operatora'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='zwrócono'),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='mode',
            field=models.CharField(choices=[('DEMO', 'Tryb demo'), ('LIVE', 'Tryb produkcyjny')], default='DEMO', max_length=10, verbose_name='tryb'),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='zmieniono'),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='zmienił(a)'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='kwota'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='event_type',
            field=models.CharField(max_length=100, verbose_name='typ'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='is_demo',
            field=models.BooleanField(editable=False, verbose_name='demo'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='orders.order', verbose_name='zamówienie'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='payload_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='skrót treści'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='przetworzono'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='processing_status',
            field=models.CharField(choices=[('RECEIVED', 'Odebrany'), ('PROCESSED', 'Przetworzony'), ('DUPLICATE', 'Duplikat'), ('IGNORED', 'Zignorowany'), ('ERROR', 'Błąd')], default='RECEIVED', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='provider',
            field=models.CharField(choices=[('DEMO', 'Demo (waluta wirtualna)'), ('STRIPE', 'Stripe')], max_length=10, verbose_name='operator'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='provider_event_id',
            field=models.CharField(max_length=200, verbose_name='ID zdarzenia u operatora'),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='otrzymano'),
        ),
    ]
