# Generated by Django 6.0.6 on 2026-10-01 12:21

import django.db.models.deletion
from django.db import migrations, models


def link_existing_entries(apps, schema_editor):
    """Backfill AuditLog.event from entity_type/entity_id for entries written
    before the column existed (new ones get it from services.log_action)."""
    AuditLog = apps.get_model("auditlog", "AuditLog")
    sources = {
        "Order": apps.get_model("orders", "Order"),
        "Ticket": apps.get_model("tickets", "Ticket"),
        "TicketPool": apps.get_model("events", "TicketPool"),
    }
    Event = apps.get_model("events", "Event")
    for entry in AuditLog.objects.filter(event__isnull=True).iterator():
        event_id = None
        if entry.entity_type == "Event":
            if Event.objects.filter(pk=entry.entity_id).exists():
                event_id = entry.entity_id
        elif entry.entity_type in sources:
            event_id = (
                sources[entry.entity_type].objects.filter(pk=entry.entity_id)
                .values_list("event_id", flat=True).first()
            )
        if event_id:
            AuditLog.objects.filter(pk=entry.pk).update(event_id=event_id)


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_polish_field_labels'),
        ('events', '0009_polish_field_labels'),
        ('orders', '0004_polish_field_labels'),
        ('tickets', '0003_polish_field_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='events.event', verbose_name='wydarzenie'),
        ),
        migrations.RunPython(link_existing_entries, migrations.RunPython.noop),
    ]
