# Generated by Django 6.0.6 on 2026-06-11 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Oczekuje'), ('SENT', 'Wysłany'), ('FAILED', 'Błąd')], default='PENDING', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='orders.order')),
            ],
            options={
                'verbose_name': 'e-mail (kolejka)',
                'verbose_name_plural': 'e-maile (kolejka)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='tickets_ema_status_6b543b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('short_code', models.CharField(max_length=12, unique=True, verbose_name='kod biletu')),
                ('qr_token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ISSUED', 'Wydany'), ('CHECKED_IN', 'Wykorzystany (wejście)'), ('REFUNDED', 'Zwrócony'), ('CANCELLED', 'Anulowany'), ('INVALIDATED', 'Unieważniony')], default='ISSUED', max_length=20)),
                ('is_demo', models.BooleanField(editable=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_checked_in', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.event')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='orders.order')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.ticketpool')),
            ],
            options={
                'verbose_name': 'bilet',
                'verbose_name_plural': 'bilety',
                'ordering': ['-issued_at'],
                'indexes': [models.Index(fields=['event', 'status'], name='tickets_tic_event_i_d07e31_idx'), models.Index(fields=['buyer_email'], name='tickets_tic_buyer_e_182ded_idx')],
            },
        ),
    ]
