# Generated by Django 6.0.6 on 2026-06-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-issued_at'], 'permissions': [('checkin_ticket', 'Może odprawiać bilety przy wejściu')], 'verbose_name': 'bilet', 'verbose_name_plural': 'bilety'},
        ),
    ]
