# Generated by Django 6.0.6 on 2026-10-01 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_polish_field_labels'),
        ('orders', '0004_polish_field_labels'),
        ('tickets', '0002_alter_ticket_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailoutbox',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='próby'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='body_html',
            field=models.TextField(blank=True, verbose_name='treść (HTML)'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='body_text',
            field=models.TextField(blank=True, verbose_name='treść (tekst)'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='utworzono'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='last_error',
            field=models.TextField(blank=True, verbose_name='ostatni błąd'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='orders.order', verbose_name='zamówienie'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='wysłano'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='subject',
            field=models.CharField(max_length=300, verbose_name='temat'),
        ),
        migrations.AlterField(
            model_name='emailoutbox',
            name='to_email',
            field=models.EmailField(max_length=254, verbose_name='adresat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='buyer_email',
            field=models.EmailField(max_length=254, verbose_name='e-mail kupującego'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='anulowano'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='wejście'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_checked_in', to=settings.AUTH_USER_MODEL, verbose_name='wpuścił(a)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.event', verbose_name='wydarzenie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_demo',
            field=models.BooleanField(editable=False, verbose_name='demo'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issued_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='wydano'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='orders.order', verbose_name='zamówienie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.ticketpool', verbose_name='pula'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='qr_token_hash',
            field=models.CharField(editable=False, max_length=64, unique=True, verbose_name='skrót tokenu QR'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='zwrócono'),
        ),
    ]
